/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.quizmaker.StudentFrames;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author szymo
 */
public class GradesFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form GradesFrame
     */
    public GradesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Grades = new javax.swing.JList<>();
        StudentName = new javax.swing.JTextField();
        Average = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Student Grade");
        setMaximumSize(new java.awt.Dimension(806, 400));
        setMinimumSize(new java.awt.Dimension(806, 400));
        setPreferredSize(new java.awt.Dimension(806, 400));

        Grades.setVisible(false);
        jScrollPane1.setViewportView(Grades);

        SaveButton.setText("Save User");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Average, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(StudentName, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveButton)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(Average, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Average.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        StudentName.setEditable(false);
        connectWithStudentProfile();
        getStudentGrades();
    }//GEN-LAST:event_SaveButtonActionPerformed

    
    private void connectWithStudentProfile() {
        String filename = "Profile.bin";
        File file = new File(filename);
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (Exception e) {
                System.out.println("Nie można utworzyć pliku");
            }
        }
        studentProfile = file;
    }
    
    private void getStudentGrades() {
        String filename = "Profile.bin";
        String[] grades = getLines(filename);
        DefaultListModel model = new DefaultListModel();
        ListModel model2 = Grades.getModel();
        for(String g:grades){
            model.addElement(g);
        }
        Grades.setModel(model);
    }
    
    public static String[] getLines(String fileName) {
        String content = readFromFile(fileName);
        return content.split("\n");
    }
    
    public static String readFromFile(String fileName) {
        String url = null;
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(fileName))) {
            url = (String) ois.readObject();
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        return url;
    }
    
    private File studentProfile;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Average;
    private javax.swing.JList<String> Grades;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField StudentName;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
